### ISSUE TITLE
Working model?

### ISSUE THREAD

**Issue by OfficePossum** [TheRealBolle/Performer-SE-PL-CL#1]
Hello I would like to ask if you have made a working model for this project?

**Comment by TheRealBolle** [comment]
What do you mean? The recreated PCBs are confirmed to work just fine by several others as well as myself.

**Comment by OfficePossum** [comment]
Sorry, I am completely new to hardware and was trying to find a project that I could to assemble to make a accelerator card for my Mac SE. I just wanted to know if your project was confirmed to work. 

I asked a similar question in another person's repo and they referred to this project  instead.
